SERVER_HOST = '0.0.0.0'
SERVER_PORT = 1234

DATABASE_HOST = 'mysql93.1gb.ru'
DATABASE_PORT = 777
DATABASE_NAME = 'gb_4stor'
DATABASE_USER = 'gb_4stor'
DATABASE_PASSWORD = '339a6zf9auiw'

WS_CLOSE = 'CLOSE'
WS_COMMON_START_SYNC = 'COMMON_START_SYNC'
WS_START_SYNC = 'START_SYNC'
WS_PAGE_SYNCHED = 'PAGE_SYNCHED'
WS_END_SYNC = 'END_SYNC'
WS_COMMON_END_SYNC = 'COMMON_END_SYNC'